include: package:lints/recommended.yaml

linter:
  rules:
    - always_declare_return_types
    - avoid_print
    - cancel_subscriptions
    - close_sinks
    - literal_only_boolean_expressions
    - prefer_single_quotes
    - public_member_api_docs
    - unnecessary_late
    - use_build_context_synchronously
